### ISSUE TITLE
GUI don't work

### ISSUE THREAD

**Issue by ClemFR** [MichaelHillcox/XRay-Fabric#1]
When I press the key to show the GUI, the game show me only my mouse cursor

**Comment by MichaelHillcox** [comment]
It's as if the mod isn't finished?

**Comment by znopp** [comment]
I am assuming you do not know why or how to fix it, right?

**Comment by MiniCoder11** [comment]
> I am assuming you do not know why or how to fix it, right? 

He is still working on this mod as a side project and it isn't his main focus. There are many unfinished aspects of the mod that he will complete if he feels like it.

**Comment by znopp** [comment]
> > I am assuming you do not know why or how to fix it, right?
> 
> He is still working on this mod as a side project and it isn't his main focus. There are many unfinished aspects of the mod that he will complete if he feels like it.

I understand. Do you know of any other xray mods that work for 1.16.4 fabric?

**Comment by MiniCoder11** [comment]
> I understand. Do you know of any other xray mods that work for 1.16.4 fabric?

I can semi-confidently say that there is no other alternative for Fabric X-ray mods. The best workaround you can use would be to install the Wurst Client as a Fabric mod although that would install many other utilities that aren't allowed on most servers (I am not recommending this solution, just informing you of its existence).

**Comment by znopp** [comment]
Thanks to some help from a friend of mine, he pointed out that the gui java file is literally empty. the only thing it does is do something with fullscreen, which is why the mouse appears. There is no menu.

**Comment by NotGeri** [comment]
> Thanks to some help from a friend of mine, he pointed out that the gui java file is literally empty. the only thing it does is do something with fullscreen, which is why the mouse appears. There is no menu.

As if the mod wasn't finished. SMH

**Comment by MichaelHillcox** [comment]
I will finish this mod at some point. I want to use it as the basis for the Forge version as well so I'm trying to do this right in terms of render caching and smarter searching algorithms. As it is, the Forge version has a huge performance impact. It searches millions of blocks every tick regardless of it it knows about those blocks. The Gui also needs some work :D I'm also learning all about the Fabric API at the same time so you know, it's not super simple for me. I also also also don't have the time.

Thanks for your understanding.
