### ISSUE TITLE
Game won't launch with Xray installed

### ISSUE THREAD

**Issue by Miles8704** [MichaelHillcox/XRay-Fabric#10]
**Describe the bug**
When clicking to launch minecraft fabric 1.16.5 with xray installed the launcher closes as per usual but the game itself never launches. I've removed all other mods so its just xray and fabric api in my mods folder and the issue persists. I tried a previous fabric version, same issue. Restarted my game multiple times, deleted and reinstalled fabric and xray, issue persists no matter what i do. Also after this happens and i try and launch again it gives me the warning that i already have a game instance open even though task manager shows otherwise (activity monitor does show some activity tho)

**To Reproduce**
1. Download Fabric and Api (v0.11.3 launcher, API 0.32.5)
2. Download Xray Fabric (v0.5.0
3. drop Xray and F API in mods folder
4. launch game

**Expected behavior**
i expect the game itself to, ya know, launch :)

**Minecraft Environment**
 - Minecraft Version: [1.16.5]
 - XRay Mod Version: [0.5.0]
 - Fabric API v0.32.5
 - Fabric v0.11.3
 
**Additional context**
I've used this mod many times before in forge and i believe fabric as well, i've been modding for near a decade so i would like to think i know what i'm doing but maybe i'm missing something. Helps appreciated, thanks :)

**Comment by steven-bleakvoltiare** [comment]
how to fix though

**Comment by MichaelHillcox** [comment]
Can you attach a crash log?
