### ISSUE TITLE
Implementing an auto-rescan

### ISSUE THREAD

**Issue by Lord-Memester** [MichaelHillcox/XRay-Fabric#12]
Possibly a configurable thing? Just that I've noticed that it doesn't actually ever check to see if anything's changed, which you (currently) have to do yourself by disabling and re-enabling. 30 or 10 seconds seems like a good baseline for a refresh/check rate.

**Comment by MichaelHillcox** [comment]
You mean for placing and removing blocks?

**Comment by randomairborne** [comment]
Yeah, when you mine a block, if it was being xrayed for you need to toggle
on/off before the outline disapears

**Comment by PixelTomato** [comment]
Maybe if the rescan was tied to chunk updates you could scan only the updated chunks to save on performance? You're probably already doing that but I have not checked through the code in quite some time.

**Comment by MichaelHillcox** [comment]
This should be done now
