### ISSUE TITLE
Game won't launch when there are configs saved from previous use of this mod.

### ISSUE THREAD

**Issue by 1schlick** [MichaelHillcox/XRay-Fabric#13]
When you use this mod for the first time, the game lanuches and you are able to use xray like normal and add blocks to the search.

When you quit the game, the configs are saved in the configs folder in the minecraft folder.

If you try to start the game again, it will crash. The only way you can fix this is by deleting the advanced xray folder inside the configs folder.

**Comment by MichaelHillcox** [comment]
Can you provide a crash log

**Comment by 1schlick** [comment]
Sorry I shouldn't have said crashed. The game doesn't actually crash, it just fails to launch and doesn't even create a game window. You can quit the process "java" in activity monitor which will result in the game crashing with exit code 0.
