### ISSUE TITLE
Minecraft runs in background but doesn't show

### ISSUE THREAD

**Issue by Bleakvoltaire** [MichaelHillcox/XRay-Fabric#15]
**Describe the bug**
Minecraft won't open with advanced xray mod on. It shows java is running in the background but the window is not showing. It used to work but not anymore.

**To Reproduce**
1. Put Advanced xray mod in mods folder
2. Put fabric api in mods folder

**Expected behavior**
it opens

**Minecraft Enviorment**
 - Minecraft Version: 1.16.5
 - XRay Mod Version: 0.5.0
 - Fabric Version: 0.11.6
 - Optifine version: G8

**Additional context**
Im in macos.

**Comment by PixelTomato** [comment]
This issue may be related to MacOS/Java compatibility issues because this same problem happens for a large amount of other Fabric mods that work on Windows 10.
