### ISSUE TITLE
Crash to desktop when activating xray feature on 1.17

### ISSUE THREAD

**Issue by ShakataGaNai** [MichaelHillcox/XRay-Fabric#16]
**Describe the bug**
Crash to desktop when pressing "\" (turn on xray). 

**To Reproduce**
1. Launch 1.17 using no mods except fabric (of course) and advanced-xray-fabric-21w06a-0.5.0s . 
2. Wait until loaded into the game
3. Press \

**Expected behavior**
Expect it not to crash. 

**Minecraft Enviorment**
 - Minecraft Version: 1.17
 - XRay Mod Version: advanced-xray-fabric-21w06a-0.5.0s
 - Mod Pack & Version if applicable: fabric-api-0.35.2+1.17. Fabric Loader 0.11.6.

**Additional context**
I realize 1.17 is brand new and there are lots of mod compatibility upgrades going on right now. However I didn't see any reports for this crash (`java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.color3f(float, float, float)'`) so thought I should report it. The previous version of Fabric Xray for 1.16.5 did work in this exact same configuration. So the "only" thing that has changed is server and client upgrade to 1.17. Crash report attached.

[crash-2021-06-17_21.58.27-client.txt](https://github.com/MichaelHillcox/XRay-Fabric/files/6674713/crash-2021-06-17_21.58.27-client.txt)

**Comment by MichaelHillcox** [comment]
Wrong mod version for 1.17. You want 0.6.0 from curse

**Comment by ShakataGaNai** [comment]
Confirmed. My apologies. For once going to the source was the wrong answer :-)
