### ISSUE TITLE
the outlines have not left when i removed the mod

### ISSUE THREAD

**Issue by KyeDaniels** [MichaelHillcox/XRay-Fabric#18]
the outlines have not disapeared when i removed the mod, and appear in the same place of EVERY SERVER, i used it for my survival but now i cannot remove the outlines.
(the outlines outline air and leaves etc, not the blocks i had originaly set, just randon scattered outlines)

I logged out of my singleplayer world and removed the mod from my folder
i then logged into my online server i moderate and it haddnt gone, with all the outlines in the same place as before.

i didnt expect it to not remove the outline, and when booting up the mod again to fix it, it was a clean canvace, nothing to remove.

i will get screenshots if nessasary but i think i made myself clear
(i cant open minecraft at the moment due to having chrome open)

 - Minecraft Version: [1.16.5]
 - XRay Mod Version: [1.16.5]

i have tried all i could think of, anyone had this issue or know how to fix it? please let me know.

**Comment by MichaelHillcox** [comment]
Don't use on servers, no support given for people that use this mod on servers.

**Comment by KyeDaniels** [comment]
> Don't use on servers, no support given for people that use this mod on servers.

i didnt use it on servers
i use it on my singleplayer world
i removed the mod before going onto the server and the outlines are still there

**Comment by MichaelHillcox** [comment]
That's not possible, you either have the mod in you mods folder or you dont

>  and appear in the same place of EVERY SERVER

**Comment by KyeDaniels** [comment]
thats the issue, i took it out my mods folder and the outlines are still there from my world
ive tried looking for a cash or something to delete but nothing
i even deleted the mod and it didnt work.

the outlines are now in every world/server i join in the same places and i cant get rid of them

**Comment by KyeDaniels** [comment]
> That's not possible, you either have the mod in you mods folder or you dont
> 
> > and appear in the same place of EVERY SERVER

just noticed i said every server without explaining, i joined a server after removing the mod and saw the outlines, so i joined other servers to see if its just a bug on that one and saw that no matter what server or world i joined i see outlines
