### ISSUE TITLE
Huge FPS drop

### ISSUE THREAD

**Issue by Yokoo2** [MichaelHillcox/XRay-Fabric#19]
Whenever I activate XRay I drop from 600FPS to 40FPS

**Comment by MichaelHillcox** [comment]
This is normal, please use a smaller radius. I'm working on improving the performance for the Fabric version of the mod but have very little time to do so

**Comment by Yokoo2** [comment]
I have the radius on 4. If I put it on 2 I get more FPS but it's not even worth using anymore.

**Comment by randomairborne** [comment]
2 is 2 *chunks*, not 2 blocks

**Comment by Prestomagic514** [comment]
can i get it

**Comment by MichaelHillcox** [comment]
Should be fixed now (1.18.2 release)
