### ISSUE TITLE
Notify me when it's released please

### ISSUE THREAD

**Issue by Magnogen** [MichaelHillcox/XRay-Fabric#2]
Hey bud, I'm so glad you've done this - my laptop is really bad at playing the game without Sodium lmao. Just wondering if there's a tutorial for installing your mod. Thanks in advance!

**Comment by MichaelHillcox** [comment]
Mods not finished yet so it's not ready to be installed. Sorry.

**Comment by Magnogen** [comment]
Okay cool, when it's done could you reply so I'm notified? Thanks bud

**Comment by MichaelHillcox** [comment]
If I remember, I'll leave this issue open

**Comment by hetile1** [comment]
+1 (for notification purposes)

**Comment by Magnogen** [comment]
> +1 (for notification purposes)

Does this mean it's done? Or are you notifying them to notify me...

**Comment by MichaelHillcox** [comment]
Not yet

**Comment by farjarhoe** [comment]
So I didn't see this issues page and I downloaded everything and compiled it myself, so I guess I'm an unintentional bug tester. The rxay runs fine but the gui doesn't open up (i remapped the button to z and the game just pauses and shows the mouse, it exits fine when I hit escape).

**Comment by MichaelHillcox** [comment]
If you can compile the code, you should be able to look in the Gui file and see that it has nothing in it? It's clearly stated in the readme that this mod isn't finished yet.

**Comment by farjarhoe** [comment]
I wasn't being critical man, you're a good developer. I honestly just wasn't paying attention.

**Comment by ToastyPawf** [comment]
(Leaving a comment here so that I can get notified when this is done)

**Comment by Kaen-1** [comment]
same

**Comment by AlexplaysVR** [comment]
same

**Comment by znopp** [comment]
might as well also leave a comment here

**Comment by randomairborne** [comment]
Is a CurseForge page planned for the first release?

**Comment by MichaelHillcox** [comment]
Yes :+1: I will update everything once I have a finished version. As well as pinging everyone in this channel

**Comment by mvilk** [comment]
👍

**Comment by NightHunter56** [comment]
Comment For Being Notified

**Comment by kuamarin** [comment]
**Comment For Being Notified**

**Comment by Magnogen** [comment]
Wow your mod has become popular lmao

**Comment by Frank-jar** [comment]
might as well also leave a comment here

**Comment by NatoBoram** [comment]
Y'all realize you can subscribe to releases, right?

![image](https://user-images.githubusercontent.com/10495562/105768933-1413b380-5f2b-11eb-84e9-fdcf8f24d379.png)

**Comment by NightHunter56** [comment]
Thanks!!!!

**Comment by Magnogen** [comment]
> Y'all realize you can subscribe to releases, right?

Oh hey, I did not know that. very handy for other projects I'm watching. thanks mate

**Comment by iCollin** [comment]
hello, if you need to use an xray fabric mod now, I made a working fork. there is some info on how to use in the readme.
it is missing many features of this great mod, but if you are like me and would like a simple version now, check out the fork here:

https://github.com/iCollin/XRay-Fabric

**Comment by iCollin** [comment]
hello, if you need to use an xray fabric mod now, I made a working fork. there is some info on how to use in the readme.
it is missing many features of this great mod, but if you are like me and would like a simple version now, check out the fork here:

https://github.com/iCollin/XRay-Fabric

Many thanks to the creator of this project for making this possible. I look forward to your proper release :)

**Comment by MichaelHillcox** [comment]
Hay, thanks for the above, it'll give people a good stop gap, I'd request that you don't release it on CurseForge just so we don't have two versions of the Fabric mod floating around. 

*Note*: I am still working on this project it is being actively developed, it will get completed soon, I'm just struggling to find time to fit in development time for it. I am also new to the fabric eco system so it's all new to me. I'm setting up a Discord server to help keep everyone updated on the mods updates and releases. I'll post a link here once it's ready :D

**Comment by iCollin** [comment]
@MichaelHillcox I’ve added you on discord, please accept when you get the chance. I could be interested in contributing to this mod.

**Comment by NightHunter56** [comment]
How Long Do You Think This Mod Will Take To Be Done

**Comment by MichaelHillcox** [comment]
For anyone instrested: Feel free to join my Discord server for specific updates and to ask any questions if you have any https://discord.gg/yYNuqJxucJ

Using XRay basically has no impact on the games performance now due to a cool new render caching system. Now it's time to make the searching for blocks a hell of a lot more performant :D

**Comment by Azmexxx** [comment]
which xray mod is going to be better I collins or

**Comment by NightHunter56** [comment]
What Do You Mean I Collin Version Is Just A Fork That Is There Until This Version Is Properly Released That Verion Does Not Even Have  Gui For Blocks Use This When It Comes out

**Comment by MichaelHillcox** [comment]
I Collins version it literally a less in dev version of this code. His simply allows you to configure blocks where as I'm currently focused on making the mod have a super performant scanning and rendering system to allow for huge chunk radius's. I thank ICollin for his help getting people am early version but as we've already discussed privately, his is just a stop gap. He's got more time than me haha.

**Comment by iCollin** [comment]
^ @MichaelHillcox is correct, my version is missing features and it is not optimized. It does kinda have a GUI tho :wink:

I only posted it in case anybody cannot wait to use XRay, and I will likely make my repo private once this mod is released.

**Comment by NightHunter56** [comment]
Today This Issue Is I Month Old

**Comment by Magnogen** [comment]
New release! Pog pog pog pog pog pog pog pog! WOOOOO OOOOOOO!

**Comment by MichaelHillcox** [comment]
The first version of Advanced XRay for Fabric has been released :tada: !!! It's only a Beta right now but it's functional... Go break it :smile:

**Github**
https://github.com/MichaelHillcox/XRay-Fabric/releases/tag/v1.16.5-0.5.0

**Curse (not approved yet)**
https://www.curseforge.com/minecraft/mc-mods/advanced-xray-fabric-edition

Please note, this isn't done, no where near it, I've just fast tracked a release for everyone that has been asking. I'll be fixing any bugs and continuing to work on the much better version of this mod in the mean time.

**Comment by posEmf** [comment]
when will it be released from beta, and is it compatible with sodium?

**Comment by MichaelHillcox** [comment]
Yes, it already is I think and no? Yes? not tested
