### ISSUE TITLE
Wire Frame Remains After Mining a Block

### ISSUE THREAD

**Issue by numeralnathan** [MichaelHillcox/XRay-Fabric#22]
**Describe the bug**
The wire frame remains after mining a block.

**To Reproduce**
1. Turn on Xray
2. Find a block that has a wire frame around it
3. Mine the block so the block becomes air
4. Notice that the wire frame is still around the empty block

**Expected behavior**
I expect the wire frame to disappear when mining a block.

**Minecraft Enviorment**
 - Minecraft Version: 1.17.1
 - XRay Mod Version: 0.6.0 build 8
 - Fabric Version: 0.8.2
 - Fabric API Version: 0.41.0

**Comment by MichaelHillcox** [comment]
Should be fixed now (1.18.2 release)
