### ISSUE TITLE
Xray incompadibility

### ISSUE THREAD

**Issue by ghost** [MichaelHillcox/XRay-Fabric#23]
Xray will not work with optifabric

**Comment by MichaelHillcox** [comment]
This known, I won't be fixing it, optifine is closed source and I don't care to figure out the issue. Also, check the pinned issues... I've explained this in detail.

**Comment by SmokePlumes** [comment]
Does not show any Xray in Minecraft 1.18.1F abric

**Comment by SmokePlumes** [comment]
Does not show Xray in Minecraft 1.18.1 Fabric
