### ISSUE TITLE
Running Xray on server

### ISSUE THREAD

**Issue by itsdinkd** [MichaelHillcox/XRay-Fabric#24]
You mentioned on curseforge you do not support running it on servers, however, you have not done anything to prevent the use of it on servers when you easily can. 

Please make this mod support server side and create a config option to allow server owners to enable to check for clients running the mod and blocking it from use.

**Comment by red2blue** [comment]
If you think about it, doing this will get you more downloads, as it would be included in modpacks to prevent usage.

**Comment by MichaelHillcox** [comment]
I can't do that easily. That's not true haha

**Comment by MichaelHillcox** [comment]
To expand on this, my mod is under the MIT license. This means, if I build in support to go against users wishes, they can simply make a copy of my mod, delete that code and we're back in the same issue again but now I have no control of the mod and can't keep its structure, Id, and code consistent for servers to write their own blockers in that use those consistent aspects. Just check this projects forks, people fork the project, change the mod or name, then do fuck all else with it. It's just them making small modifications to bypass server protections. 

I could build a partnering mod for servers specifically that blocks this but I'll just do what most good server protectors already do. 

Hope that explains my stance a bit.

**Comment by itsdinkd** [comment]
> To expand on this, my mod is under the MIT license. This means, if I build in support to go against users wishes, they can simply make a copy of my mod, delete that code and we're back in the same issue again but now I have no control of the mod and can't keep its structure, Id, and code consistent for servers to write their own blockers in that use those consistent aspects. Just check this projects forks, people fork the project, change the mod or name, then do fuck all else with it. It's just them making small modifications to bypass server protections.
> 
> I could build a partnering mod for servers specifically that blocks this but I'll just do what most good server protectors already do.
> 
> Hope that explains my stance a bit.

Uh... I guarantee you that 99% of the people that use a xray mod are not java developers. Also.. why would they do that when you could add a option in the config to toggle xray prevention? Makes zero sense lmfao

**Comment by MichaelHillcox** [comment]
Cute. I'm not changing my mind here, it would be trivial to make these changes. If you feel like it's needed, make a server companion plug-in and PR some code. I'll accept it and I'll be sure to let you know once the inevitable fork and re-release of my mod pops up because of this feature.
