### ISSUE TITLE
Game stops when I try to use in Nether

### ISSUE THREAD

**Issue by ItsYaBoyYeeter** [MichaelHillcox/XRay-Fabric#29]
When I added ancient Debris in the menu and Turned the X-Ray on my sounds stopped and then the game stopped working.
Then I had to manually crash my game using the F3+C keybind

**To Reproduce**
1. Open the menu to add blocks
2. add ancient debris.
3. Press the keybind to turn x-ray on. 

**Expected behavior**

**Minecraft Enviorment**
 - Minecraft Version: 1.18.1
 - XRay Mod Version: 1.18-0.7.0-build.10

**Comment by enagimintas** [comment]
what xray distance it was?

**Comment by ItsYaBoyYeeter** [comment]
It was at 2. But I think it's because of the lava. When I turned the lava off it worked relatively fine.

**Comment by MichaelHillcox** [comment]
Attach a crashlog if this still happens
