### ISSUE TITLE
Game will not render blocks in 1.18 with mod

### ISSUE THREAD

**Issue by PiglinPlayz** [MichaelHillcox/XRay-Fabric#30]
**Describe the bug**
When playing fabric mc with 1.18 xray i end up having blocks not render and times still rendering. Like blocks wont show and some will show after i break the block. Also when this happens the outlines will not render. 
**To Reproduce**
1. playing mc all times render 
2. playing mc then dye from something 
3. blocks slowly de render from my game 
4. all blocks are gone after i die again. 
5. aster this happens nothing will render including the xray outlines. 

**Expected behavior**
I expected to have xray to work on with no issues. 
**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: 1.18
 - XRay Mod Version: advanced-xray-fabric-1.18-0.7.0-build.10.jar
 - Mod Pack & Version if applicable: no mod pack just this and fabric api 
 - Fabric Version if applicable: 0.12.12
[debug.log](https://github.com/MichaelHillcox/XRay-Fabric/files/7877052/debug.log)
[latest.log](https://github.com/MichaelHillcox/XRay-Fabric/files/7877053/latest.log)

**Comment by PiglinPlayz** [comment]
[debug.log](https://github.com/MichaelHillcox/XRay-Fabric/files/7877049/debug.log)
[latest.log](https://github.com/MichaelHillcox/XRay-Fabric/files/7877050/latest.log)

**Comment by MichaelHillcox** [comment]
Should be fixed now (1.18.2 release)
