### ISSUE TITLE
Weird Key Binds

### ISSUE THREAD

**Issue by AverageComet250** [MichaelHillcox/XRay-Fabric#7]
**Describe the bug**
When I try and use the mod, nothing happens when I click on Z or \ but the x-ray turns on when I click the # key, but it's useless since I can't work out how to open the gui to add blocks. Note that I'm on a British qwerty keyboard.

**To Reproduce**
1. Start minecraft
2. go on a world
3. try pressing \ and z
4. try pressing #

**Expected behavior**
1. start minecraft
2. open a world
3. press z
4. the config menu appears
5. press \
6. see the xray turn on

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: 1.16.5
 - XRay Mod Version: 0.4.4
 - None, however i have litematica, phosphor and optifine installed
 - ~~Forge~~ Fabric Version is 0.11.2 and installed through multimc

**Additional context**

**Comment by randomairborne** [comment]
the correct keyind is g.

**Comment by AverageComet250** [comment]
thanks!
