### ISSUE TITLE
doesn't work in nether

### ISSUE THREAD

**Issue by SaltyTiefling** [MichaelHillcox/XRay-Fabric#9]
**Describe the bug**
it won't show me anything in the nether
**To Reproduce**
1. go to the nether

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11724313/111919597-1279ee00-8a8b-11eb-9e2b-0fec6b038668.png)

**Minecraft Enviorment**
 - Minecraft Version: 1.16.5
 - XRay Mod Version: advanced-xray-fabric-0.5.0

**Comment by randomairborne** [comment]
What if you turn up the scan distance?

**Comment by SaltyTiefling** [comment]
> What if you turn up the scan distance?

I have to change everything but it won't work

**Comment by randomairborne** [comment]
![image](https://user-images.githubusercontent.com/69158910/111920860-ff4d2b00-8a56-11eb-82ea-71bb6dc45d7f.png)
Seems to work fine.... is Xray enabled and is the block you are looking for added?

**Comment by SaltyTiefling** [comment]
> ![image](https://user-images.githubusercontent.com/69158910/111920860-ff4d2b00-8a56-11eb-82ea-71bb6dc45d7f.png)
> Seems to work fine.... is Xray enabled and is the block you are looking for added?

I am searching for gold ore and it won't show even when looking at it. it works fine in the over world
![image](https://user-images.githubusercontent.com/11724313/111920912-ff1e5100-8a91-11eb-8000-bbcbec9a92fd.png)

**Comment by randomairborne** [comment]
Works fine for me, this is more of a tech support thing. check out Mikey's [discord](https://discord.gg/h6DZ3zkE) for simpler mod support

**Comment by SaltyTiefling** [comment]
oke I found that it's a problem with the other mods apparently
does anyone know which it is?
![image](https://user-images.githubusercontent.com/11724313/111921055-cdf25080-8a92-11eb-8102-646268b85c34.png)

**Comment by randomairborne** [comment]
OptiFine and OptiFabric are incompatible with this mod.

**Comment by SaltyTiefling** [comment]
indeed I have to turn off my shader to see them in the nether but then it works
